spring:
  application:
    name: rate-my-pc-bro
  
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3

server:
  port: 8080
  servlet:
    context-path: /api
